name: My workflow
on: [push]
jobs:
  app_block:
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
      - run: |
         cat <<-EOF > $BUNDLE_GEMFILE 
         source "https://rubygems.org"
         ruby "3.3.0"
         gem 'rails', '~> 7.1', '>= 7.1.3'
         EOF
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Commit changed files back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated commit
